"""Pack Blender views as exact RGB222/binary-alpha PNG and RGBA2222 bytes."""
from pathlib import Path
import json
from PIL import Image, ImageDraw
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'assets/car'
records=[];colors=set();views=[]
for index in range(9):
    source=Image.open(ROOT/'obj/car-raw'/f'car-{index:02d}.png').convert('RGBA')
    pixels=[];packed=bytearray()
    for r,g,b,a in source.get_flattened_data():
        if a<128: pixels.append((0,0,0,0));packed.append(0);continue
        r,g,b=(min(3,(c+42)//85) for c in (r,g,b))
        pixels.append((r*85,g*85,b*85,255));packed.append(r|(g<<2)|(b<<4)|0xc0)
        colors.add((r*85,g*85,b*85))
    image=Image.new('RGBA',source.size);image.putdata(pixels)
    assert image.getbbox() is not None
    x0,y0,x1,y1=image.getbbox()
    assert x0>0 and y0>0 and x1<64 and y1<48, ('Clipped sprite',index,image.getbbox())
    image.save(OUT/f'car-{index:02d}.png')
    (OUT/f'car-{index:02d}.rgba2222').write_bytes(packed)
    records.append({'index':index,'yaw_degrees':-30+7.5*index,'width':64,'height':48,'bytes':len(packed),'bounds':[x0,y0,x1,y1]})
    views.append(image)
# Nearest-neighbor enlarged proofs, with a constant canvas per view.
sheet=Image.new('RGB',(9*192,174),(38,43,48));draw=ImageDraw.Draw(sheet)
for i,view in enumerate(views):
    large=view.resize((192,144),Image.Resampling.NEAREST)
    sheet.paste(large,(i*192,0),large)
    draw.text((i*192+60,151),f'{records[i]["yaw_degrees"]:+g} deg',fill='white')
sheet.save(OUT/'yaw-sheet.png')
# At intended screen size, place the straight view on the current road capture.
road=Image.open(ROOT/'docs/straight-road.png').convert('RGBA').resize((320,240),Image.Resampling.NEAREST)
road.alpha_composite(views[4],(128,171))
road.resize((960,720),Image.Resampling.NEAREST).save(OUT/'road-mockup.png')
(OUT/'sprites.json').write_text(json.dumps({'format':'RGBA2222: R low two bits, G bits 2-3, B bits 4-5, A high two bits','palette':sorted(colors),'view_count':9,'total_bytes':9*64*48,'framing':'fixed orthographic camera; rotate around world origin; never crop per view','views':records},indent=2)+'\n')
print(f'Exported nine 64x48 views, {len(colors)} opaque colors, {9*64*48:,} bytes total.')

header='// Generated by tools/export_car.py from the Blender yaw renders.\n#pragma once\n#include <stdint.h>\nnamespace rally {\nstatic const uint8_t CarPixels[9][3072] = {\n'
for i in range(9):
    data=(OUT/f'car-{i:02d}.rgba2222').read_bytes()
    header+='  {\n'+''.join('    '+','.join(map(str,data[j:j+32]))+',\n' for j in range(0,len(data),32))+'  },\n'
header+='};\n}\n'
(ROOT/'include/car.hpp').write_text(header)
