"""Generate selectable Fuji and original tri-oval tables from editable JSON cubics."""
from pathlib import Path
import bisect, json, math
ROOT=Path(__file__).resolve().parents[1]
FOLDER=ROOT/'assets/tracks'
def generate(config):
    start=config['start'];curves=config['curves'];dense=[start];origin=start
    for c1,c2,end in curves:
        for i in range(1,401):
            t=i/400;u=1-t
            dense.append(tuple(u*u*u*origin[j]+3*u*u*t*c1[j]+3*u*t*t*c2[j]+t*t*t*end[j] for j in range(2)))
        origin=end
    assert tuple(origin)==tuple(start)
    cumulative=[0.0]
    for a,b in zip(dense,dense[1:]): cumulative.append(cumulative[-1]+math.dist(a,b))
    length=config['length'];count=length//64;scale=length/cumulative[-1]
    assert count and length==count*64
    def point(distance):
        distance%=cumulative[-1]
        i=bisect.bisect_right(cumulative,distance)-1
        f=(distance-cumulative[i])/(cumulative[i+1]-cumulative[i])
        return tuple(dense[i][j]+f*(dense[i+1][j]-dense[i][j]) for j in range(2))
    records=[]
    for i in range(count):
        d=cumulative[-1]*i/count;p=point(d);a=point(d-.2);b=point(d+.2)
        dx=b[0]-a[0];dy=b[1]-a[1];norm=math.hypot(dx,dy)
        records.append((round((p[0]-start[0])*scale),round((p[1]-start[1])*scale),round(dx/norm*4096),round(dy/norm*4096)))
    assert all(-32768<=v<=32767 for r in records for v in r)
    radii=[];turns=[]
    for a,b in zip(records,records[1:]+records[:1]):
        turn=math.atan2(a[2]*b[3]-a[3]*b[2],a[2]*b[2]+a[3]*b[3]);turns.append(turn)
        if abs(turn)>.0001:radii.append(64/abs(turn))
    stem='fuji' if config['symbol']=='Fuji' else 'tri-oval'
    (FOLDER/(stem+'.csv')).write_text('sample,x,y,tangent_x_q12,tangent_y_q12\n'+''.join(f'{i},'+','.join(map(str,r))+'\n' for i,r in enumerate(records)))
    path=f'M {start[0]} {start[1]} '+' '.join('C '+' '.join(f'{x} {y}' for x,y in c) for c in curves)+' Z'
    box='80 42 160 90' if stem=='tri-oval' else '20 40 280 165'
    svg=f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="{box}" width="840" height="420"><rect x="0" y="0" width="320" height="240" fill="#15232c"/><path d="{path}" fill="none" stroke="#eee" stroke-width="3"/><circle cx="{start[0]}" cy="{start[1]}" r="3" fill="#ffcf40"/></svg>'''
    (FOLDER/(stem+'.svg')).write_text(svg+'\n')
    stats={'length':length,'samples':count,'sample_spacing':64,'minimum_sampled_radius':min(radii),'total_turn_radians':sum(turns)}
    (FOLDER/(stem+'-stats.json')).write_text(json.dumps(stats,indent=2)+'\n')
    print(config['name'],stats)
    symbol=config['symbol'];header=f'static const TrackPoint {symbol}Points[{count}] = {{\n'
    header+=''.join('    {'+','.join(map(str,r))+'},\n' for r in records)+'};\n'
    header+=f'static const TrackDef {symbol} = {{{symbol}Points,{count},{length},"{config["name"]}"}};\n'
    return header
header='// Generated by tools/generate_track.py from assets/tracks/*.json.\n#pragma once\n#include <stdint.h>\nnamespace rally {\nconstexpr int TrackCount=512, TrackStep=64;\nconstexpr int32_t TrackLength=32768; // Legacy Fuji test calibration.\nstruct TrackPoint { int16_t x,y,tx,ty; };\nstruct TrackDef { const TrackPoint *points; unsigned count; int32_t length; const char *name; };\n'
for name in ('fuji','tri-oval'):header+=generate(json.loads((FOLDER/(name+'.json')).read_text()))
(ROOT/'include/track.hpp').write_text(header+'}\n')
# Current-track overview; explicitly named originals remain alongside it.
for ext in ('svg','csv'):(ROOT/'assets'/('track.'+ext)).write_bytes((FOLDER/('tri-oval.'+ext)).read_bytes())
