"""Digitized centreline from the user-supplied arcade map; no ROM track data.

Cubic control points are hand traced in the displayed 320x200 reference's
coordinates. Resample by arc length, not Bezier parameter, into an integer table.
Only stdlib is required. Outputs are original derived geometry, not source art.
"""
from pathlib import Path
import bisect
import math
ROOT = Path(__file__).resolve().parents[1]
START = (160, 70)
# Each cubic continues from the preceding endpoint, clockwise from the top straight.
CURVES = [
    ((194,70),(234,70),(259,70)),
    ((272,70),(275,88),(261,91)),
    ((248,94),(221,89),(213,103)),
    ((207,113),(201,137),(192,147)),
    ((185,154),(171,150),(171,138)),
    ((170,127),(176,106),(176,98)),
    ((176,91),(168,92),(165,98)),
    ((158,109),(145,138),(131,145)),
    ((118,153),(97,152),(85,148)),
    ((68,142),(57,137),(51,124)),
    ((44,111),(39,91),(45,80)),
    ((48,73),(54,70),(62,70)),
    ((90,70),(128,70),START),
]
def main():
    dense=[START]; origin=START
    for c1,c2,end in CURVES:
        for i in range(1,401):
            t=i/400; u=1-t
            dense.append(tuple(u*u*u*origin[j]+3*u*u*t*c1[j]+3*u*t*t*c2[j]+t*t*t*end[j] for j in range(2)))
        origin=end
    cumulative=[0.0]
    for a,b in zip(dense,dense[1:]): cumulative.append(cumulative[-1]+math.dist(a,b))
    count=512; length=32768; scale=length/cumulative[-1]
    def point(distance):
        distance%=cumulative[-1]
        i=bisect.bisect_right(cumulative,distance)-1
        f=(distance-cumulative[i])/(cumulative[i+1]-cumulative[i])
        return tuple(dense[i][j]+f*(dense[i+1][j]-dense[i][j]) for j in range(2))
    points=[point(cumulative[-1]*i/count) for i in range(count)]
    records=[]
    for i,p in enumerate(points):
        # Symmetric local tangent avoids unequal-segment camera-heading jumps.
        before=point(cumulative[-1]*i/count-0.2)
        after=point(cumulative[-1]*i/count+0.2)
        dx=after[0]-before[0]; dy=after[1]-before[1]; norm=math.hypot(dx,dy)
        records.append((round((p[0]-160)*scale),round((p[1]-70)*scale),round(dx/norm*4096),round(dy/norm*4096)))
    assert all(-32768<=v<=32767 for r in records for v in r)
    header='// Generated by tools/generate_track.py. Hand-traced reference, resampled by arc length.\n#pragma once\n#include <stdint.h>\nnamespace rally {\nconstexpr int TrackCount=512, TrackStep=64;\nconstexpr int32_t TrackLength=32768;\nstruct TrackPoint { int16_t x,y,tx,ty; };\nstatic const TrackPoint Track[TrackCount] = {\n'
    header+=''.join('    {'+','.join(map(str,r))+'},\n' for r in records)+'};\n}\n'
    (ROOT/'include/track.hpp').write_text(header)
    path='M 160 70 '+' '.join('C '+' '.join(f'{x} {y}' for x,y in curve) for curve in CURVES)+' Z'
    svg=f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="25 45 265 120" width="795" height="360"><rect x="25" y="45" width="265" height="120" fill="#15232c"/><path d="{path}" fill="none" stroke="#eeeeee" stroke-width="3"/><circle cx="160" cy="70" r="3" fill="#ffcf40"/><path d="M 166 59 H 182 M 178 55 L 182 59 L 178 63" fill="none" stroke="#ffcf40" stroke-width="1.5"/><text x="50" y="162" fill="white" font-size="6" font-family="sans-serif">Hand-traced reference centreline / start travels right / not surveyed geometry</text></svg>'''
    (ROOT/'assets/track.svg').write_text(svg+'\n')
    (ROOT/'assets/track.csv').write_text('sample,x,y,tangent_x_q12,tangent_y_q12\n'+''.join(f'{i},'+','.join(map(str,r))+'\n' for i,r in enumerate(records)))
    print(f'Generated {count} samples, {length} arbitrary world units, {scale:.2f} units/reference pixel.')
if __name__=='__main__': main()
