"""Deterministic infinity panorama; solid reference-blue sky and procedural scenery."""
from pathlib import Path
import math, random
from PIL import Image, ImageDraw
import agonutils
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'assets/scenery';OUT.mkdir(exist_ok=True,parents=True)
RAW=ROOT/'obj/scenery';RAW.mkdir(exist_ok=True,parents=True)
W,H=1024,103
# Sixteen RGB222 colours including rich blues, snowy whites and wooded greens.
palette=[(0,85,255),(85,85,255),(85,170,255),(170,170,255),
 (255,255,255),(170,170,170),(85,85,170),(0,85,170),
 (0,85,85),(0,85,0),(85,85,0),(85,170,85),
 (0,255,255),(85,85,85),(0,170,85),(170,170,85)]
gpl='GIMP Palette\nName: Rally scenery RGB222\nColumns: 8\n#\n'+''.join(f'{r} {g} {b}\tColour {i}\n' for i,(r,g,b) in enumerate(palette))
(OUT/'scenery.gpl').write_text(gpl)
# Solid reference-blue sky: no gradient, quantization noise or dithering.
img=Image.new('RGB',(W,H),palette[0]);draw=ImageDraw.Draw(img)
# Clouds are deterministic overlapping small lobes, baked into the same layer.
rng=random.Random(747)
for cx,cy,width in [(210,35,48),(440,22,56),(705,42,68),(910,27,38)]:
 for j in range(12):
  x=cx+rng.randrange(-width//2,width//2);y=cy+rng.randrange(-5,5)
  rx=rng.randrange(5,12);ry=rng.randrange(2,5)
  draw.ellipse((x-rx,y-ry,x+rx,y+ry),fill=palette[3])
  draw.ellipse((x-rx,y-ry-2,x+rx-2,y+1),fill=palette[4])
# Fuji-like isolated volcanic silhouette and angular snow cap.
mountain=[(14,96),(31,91),(43,82),(58,75),(68,65),(77,61),(86,69),(96,79),(111,87),(133,97)]
draw.polygon(mountain,fill=palette[7])
draw.polygon([(77,61),(86,69),(96,79),(111,87),(89,82),(81,74),(76,69),(66,82),(52,86),(68,65)],fill=palette[5])
draw.polygon([(77,61),(84,68),(88,72),(83,71),(86,76),(79,73),(76,67),(72,76),(69,74),(63,79),(68,69)],fill=palette[4])
# Periodic foothill profiles join at the panorama seam. All at infinity.
for layer,base,colour in [(0,94,palette[8]),(1,99,palette[10])]:
 points=[]
 for x in range(W):
  h=(2.3*math.sin(2*math.pi*x/W*17+layer)+1.3*math.sin(2*math.pi*x/W*43)+.8*math.sin(2*math.pi*x/W*97))
  points.append((x,round(base+h)))
 draw.polygon(points+[(W-1,H),(0,H)],fill=colour)
img.save(RAW/'scenery-source.png')
# Solid scenery is composited after sky palette conversion; never quantize it again.
img.save(OUT/'panorama.png')
image=Image.open(OUT/'panorama.png').convert('RGB');indices={c:i for i,c in enumerate(palette)}
values=[indices[c] for c in image.get_flattened_data()]
data=bytes((values[i]<<4)|values[i+1] for i in range(0,len(values),2))
(OUT/'panorama.idx4').write_bytes(data)
rgba=[0xc0|(r//85)|((g//85)<<2)|((b//85)<<4) for r,g,b in palette]
angles=[round(math.atan(i/256)*1024/(2*math.pi)) for i in range(257)]
header='// Generated by tools/generate_scenery.py.\n#pragma once\n#include <stdint.h>\nnamespace rally {\n'
for name,array,ctype in [('SceneryPalette',rgba,'uint8_t'),('SceneryPixels',data,'uint8_t'),('HeadingAtan',angles,'uint8_t')]:
 header+=f'static const {ctype} {name}[{len(array)}]={{\n'+''.join(','.join(map(str,array[i:i+32]))+',\n' for i in range(0,len(array),32))+'};\n'
(ROOT/'include/scenery_data.hpp').write_text(header+'}\n')
print('Scenery:',W,H,'indexed bytes:',len(data),'palette:',len(palette))
