"""Export sparse shared-pace routes and prove their indefinite gap invariant."""
import json
import math
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RECORDS = [(60,180,0,32), (60,180,1920,-32), (180,170,0,0),
           (60,180,0,-32), (60,180,-1920,32), (180,150,0,0)]
SINE = [round(math.sin(i*math.pi/512)*32767) for i in range(257)]


def trunc(n, d):
    return n//d if n >= 0 else -((-n)//d)


def sine(heading):
    negative = heading < 0
    h = abs(heading) % 65536
    if h >= 32768:
        h -= 32768
        negative = not negative
    if h > 16384:
        h = 32768-h
    i, f = divmod(h, 64)
    value = SINE[i] if i == 256 else SINE[i]+(SINE[i+1]-SINE[i])*f//64
    return -value if negative else value


def cycle():
    lateral = heading = forward = 0
    for index, (duration, speed, entry, rate) in enumerate(RECORDS):
        assert duration > 0 and 0 <= speed <= 300 and heading == entry
        for left in range(duration, 0, -1):
            heading += rate
            lateral += trunc(2*speed*sine(heading), 12800)
            forward += speed*2
            yield index, left-1, heading, lateral, forward
    assert heading == 0 and lateral == 0


def generate():
    rows = list(cycle())
    lo, hi = min(r[3] for r in rows), max(r[3] for r in rows)
    assert len(rows) == 600 and lo == 0
    # Base lanes -36,0,+36 with +/- mirrored half-excursion around each lane.
    maximum = max(abs(base*256+mirror*(r[3]-hi//2))
                  for base in (-36,0,36) for mirror in (-1,1) for r in rows)
    assert maximum+12*256 < 90*256
    # Longitudinal movement is identical each tick, including wrap; >=96
    # initial gaps remain >=96 indefinitely, strictly above contact length32.
    track_source=(ROOT.parent/'rally-production/include/track.hpp').read_text()
    laps={name:int(length)*100 for name,length in re.findall(
        r'TrackDef (Fuji|TriOval) = \{[^,]+,[^,]+,(\d+),',track_source)}
    assert set(laps)=={'Fuji','TriOval'}
    for lap in laps.values():
        positions = [i*10000 for i in range(6)]
        for r in rows:
            shifted = [(p+r[4]) % lap for p in positions]
            for i in range(6):
                for j in range(i):
                    gap = min((shifted[i]-shifted[j]) % lap, (shifted[j]-shifted[i]) % lap)
                    assert gap >= 9600
    header = '// Generated by tools/generate_routes.py; see assets/routes-proof.json.\n'
    header += '#pragma once\n#include <stdint.h>\nnamespace rally::game {\n'
    header += 'struct RouteRecord { uint16_t duration,speed;int16_t heading,rate; };\n'
    header += 'constexpr RouteRecord Route[]={\n'
    header += ''.join('{'+','.join(map(str,r))+'},\n' for r in RECORDS)+'};\n'
    header += 'constexpr int16_t RouteHalfExcursion='+str(hi//2)+';\n'
    header += 'constexpr int16_t RouteSine[257]={\n'
    for i in range(0,len(SINE),16):
        header += ','.join(map(str,SINE[i:i+16]))+',\n'
    header += '};\n}\n'
    (ROOT/'include/routes_data.hpp').write_text(header)
    proof = {'format':1, 'ticks':600, 'records':RECORDS, 'lateral_q8_extrema':[lo,hi],
             'max_car_centre_abs_q8':maximum, 'longitudinal_period_hundredths':rows[-1][4],
             'track_lengths_hundredths':laps,
             'minimum_admitted_gap_hundredths':9600, 'contact_length_hundredths':3200,
             'proof':'Common displacement preserves every admitted pair gap for all ticks; '
                     'periodic heading/lateral replay closes exactly. Symmetric integer sine '
                     'and matched lobe pace establish indefinite bounded lateral movement.'}
    (ROOT/'assets/routes-proof.json').write_text(json.dumps(proof,indent=2)+'\n')
    print(json.dumps(proof,indent=2))


if __name__ == '__main__':
    generate()
