"""Palette-convert the Author's source artwork to single 64x64 road billboards.

Nearest-neighbour sprite/logo scaling, no dither or perspective transform.
All inputs are local editable assets with provenance; no network access.
"""
import json
from pathlib import Path
from PIL import Image, ImageDraw

ROOT=Path(__file__).resolve().parents[1]
ASSETS=ROOT/'assets/signs'
font=json.loads((ROOT/'assets/font.json').read_text())
ships=json.loads((ASSETS/'source/ships.json').read_text())
meta=json.loads((ASSETS/'sources.json').read_text())


def text(im,word,y,colour=(255,255,255)):
    x=(64-(len(word)*6-1))//2
    for char in word:
        for row,bits in enumerate(font[char] if char!=' ' else ['00000']*7):
            for col,bit in enumerate(bits):
                if bit=='1':im.putpixel((x+col,y+row),(*colour,255))
        x+=6


def board(colour=(0,0,85)):
    im=Image.new('RGBA',(64,64));d=ImageDraw.Draw(im)
    d.rectangle((0,0,63,47),fill=(255,255,255,255))
    d.rectangle((2,2,61,45),fill=(*colour,255))
    for x in (10,50):d.rectangle((x,48,x+3,63),fill=(170,170,170,255))
    return im


def paste_fit(im,art,box):
    art=art.convert('RGBA');w,h=art.size
    scale=min((box[2]-box[0])/w,(box[3]-box[1])/h)
    size=max(1,round(w*scale)),max(1,round(h*scale))
    art=art.resize(size,Image.Resampling.NEAREST)
    im.alpha_composite(art,(box[0]+(box[2]-box[0]-size[0])//2,box[1]+(box[3]-box[1]-size[1])//2))


def rgba2(data,size):
    im=Image.new('RGBA',size)
    im.putdata([((v&3)*85,((v>>2)&3)*85,((v>>4)&3)*85,((v>>6)&3)*85) for v in data])
    return im


def pack(im):
    # Snap to the real 64-colour cube before selecting a per-sign 16-entry map.
    colours=[tuple(round(v/85)*85 for v in p[:3]) for p in im.get_flattened_data()]
    rgb=Image.new('RGB',im.size);rgb.putdata(colours)
    indexed=rgb.quantize(colors=15,method=Image.Quantize.MEDIANCUT,dither=Image.Dither.NONE)
    opaque=list(indexed.convert('RGB').get_flattened_data())
    palette=[0];values=[]
    for original,p in zip(im.get_flattened_data(),opaque):
        value=0 if original[3]<128 else 0xc0|round(p[0]/85)|(round(p[1]/85)<<2)|(round(p[2]/85)<<4)
        if value not in palette:palette.append(value)
        values.append(palette.index(value))
    assert len(palette)<=16
    palette += [0]*(16-len(palette))
    # VDP command72's 4-bit input consumes the high nibble first.
    data=[values[i]<<4|values[i+1] for i in range(0,len(values),2)]
    preview=rgba2([palette[v] for v in values],im.size)
    return data,palette,preview


signs=[]
im=board();text(im,'AGINVADORS',5,(0,255,255))
for name,colour,x in [('squid0',(255,170,85,255),9),('crab0',(85,255,255,255),34)]:
    rows=ships['invaders'][name];sprite=Image.new('RGBA',(len(rows[0]),len(rows)))
    sprite.putdata([colour if b=='1' else (0,0,0,0) for row in rows for b in row])
    im.alpha_composite(sprite.resize((sprite.width*2,sprite.height*2),Image.Resampling.NEAREST),(x,22))
signs.append(('aginvadors',im))
im=board((0,0,0));text(im,'DEFENDER',5,(85,255,255))
rows=ships['ship'];data=[ships['COLORS'][c] for row in rows for c in row]
paste_fit(im,rgba2(data,(20,9)),(8,18,56,41));signs.append(('defender',im))
im=board((0,0,0));paste_fit(im,Image.open(ASSETS/'source/nurples.png'),(3,4,61,44));signs.append(('nurples',im))
im=board();text(im,'AGON',4,(255,255,85));text(im,'JUKEBOX',37,(255,255,85))
logo=rgba2((ASSETS/'source/jukebox.rgba2').read_bytes(),(80,120))
paste_fit(im,logo,(22,13,42,35));signs.append(('jukebox',im))
im=board((0,0,0));paste_fit(im,Image.open(ASSETS/'source/extender.png').crop(meta['extender_crop']),(13,3,51,36))
text(im,'EXTENDER',37,(255,85,85));signs.append(('extender',im))
im=board((0,0,170));text(im,'AGON',36);paste_fit(im,logo,(21,3,43,34));signs.append(('agon',im))
im=board((85,0,0));text(im,'RICHARD',5);text(im,'TURNNIDGE',14);text(im,'STARSHIP',27,(255,255,85));text(im,'SENTINEL',36,(255,255,85));signs.append(('turnnidge-tribute',im))
im=board((0,85,0));text(im,"XIAN'S",6,(255,255,85));text(im,'AGON',20);text(im,'PROJECTS',34);signs.append(('xian-tribute',im))

lines=['// Generated by tools/generate_signs.py; provenance: assets/signs/sources.json.',
       '#pragma once','#include <stdint.h>','namespace rally::game {',
       'constexpr unsigned SignCount=8;','struct SignArt {uint8_t palette[16],pixels[2048];};',
       'constexpr SignArt SignArtwork[SignCount]={']
preview=Image.new('RGB',(4*192,2*192),(35,45,35))
for index,(name,im) in enumerate(signs):
    data,palette,converted=pack(im)
    lines.append('{{'+','.join(map(str,palette))+'},{')
    for i in range(0,len(data),32):lines.append(','.join(map(str,data[i:i+32]))+',')
    lines.append('}},')
    converted.save(ASSETS/(name+'.png'))
    preview.paste(converted.resize((192,192),Image.Resampling.NEAREST),(index%4*192,index//4*192),converted.resize((192,192),Image.Resampling.NEAREST))
lines+=['};','}']
(ROOT/'include/signs_data.hpp').write_text('\n'.join(lines)+'\n')
preview.save(ASSETS/'preview.png')
print('Generated eight 64x64 single-bitmap signs, 16512 embedded bytes')
