// Host-only generator: compile with -O2 -std=c++17 -Irally/include.
// stdout is the generated header; diagnostics go to stderr.
#include "road.hpp"
#include <array>
#include <vector>
#include <cstdio>
#include <cstdlib>

int main(int argc,char **argv) {
    using namespace rally;
    using View=std::array<int32_t,Bottom+2>;
    int binWorld=argc>1?std::atoi(argv[1]):16;
    if(binWorld<1 || 64%binWorld) return 1;
    std::vector<std::vector<int>> tables;
    unsigned maxBands=0;
    size_t totalViews=0;
    Road road;road.init();
    for(const TrackDef *track:{&TriOval,&Fuji}) {
        road.track=track;
        for(int32_t bin=0;bin<track->length;bin+=binWorld) {
            std::vector<View> views;
            // Quarter-world-unit coverage plus the final hundredth in the bin.
            for(int32_t offset=0;offset<=binWorld*100;offset+=25) {
                int32_t p=bin*100+(offset==binWorld*100?offset-1:offset);
                road.project(p,0);
                View view{};
                for(int y=RoadTop;y<=Bottom+1;++y) view[y]=road.centers[y];
                views.push_back(view);
            }
            totalViews+=views.size();
            // < half pixel on each complete segment leaves margin for arbitrary
            // material splits (their endpoint residual can add to the row residual).
            constexpr int ToleranceQ8=112;
            std::vector<int> boundaries{RoadTop};
            for(int start=RoadTop;start<=Bottom;) {
                int end=start+1;
                for(int candidate=end+1;candidate<=Bottom+1;++candidate) {
                    bool fits=true;
                    for(const auto &view:views) {
                        for(int y=start+1;y<candidate;++y) {
                            int64_t error=int64_t(view[start]-view[y])*(candidate-start)
                                +int64_t(view[candidate]-view[start])*(y-start);
                            if(std::abs(error)>int64_t(ToleranceQ8)*(candidate-start)) {
                                fits=false;break;
                            }
                        }
                        if(!fits) break;
                    }
                    if(!fits) break;
                    end=candidate;
                }
                boundaries.push_back(end);start=end;
            }
            if(boundaries.size()-1>maxBands) maxBands=unsigned(boundaries.size()-1);
            tables.push_back(boundaries);
        }
    }
    size_t bytes=0;
    for(const auto &table:tables) bytes+=table.size()-1;
    std::fprintf(stderr,"%zu views, %zu tables, max %u geometric bands; %zu boundary bytes + %zu offset bytes\n",
                 totalViews,tables.size(),maxBands,bytes,2*tables.size());
    if(bytes>65535) return 2;
    std::puts("// Generated by docs/tasks/RALLY-10/generate_band_table.cpp; do not edit.\n"
              "// Quarter-world-unit samples; 112/256 pixel full-segment bound.\n"
              "#pragma once\n#include <stdint.h>\nnamespace rally {");
    std::printf("constexpr int BandBinWorld=%d;\nconstexpr unsigned BandFujiOffset=%d;\n",binWorld,TriOval.length/binWorld);
    std::puts("constexpr uint16_t BandOffsets[] = {");
    size_t offset=0;
    for(const auto &table:tables) { std::printf("%zu,",offset);offset+=table.size()-1; }
    std::puts("\n};\n// Inclusive row ends; each table terminates at row 223.\nconstexpr uint8_t BandEnds[] = {");
    for(const auto &table:tables) {
        std::printf("    ");
        for(size_t i=1;i<table.size();++i) std::printf("%d,",table[i]-1);
        std::puts("");
    }
    std::puts("};\n}");
}
