#!/usr/bin/env python3
"""Generate exact material-boundary lookups; run with root .venv/bin/python."""
from __future__ import annotations

import argparse
from pathlib import Path


def generate() -> str:
    horizon, marked_top, bottom = 96, 116, 223
    half_period = 4000  # hundredths of a world unit
    depth = [0] + [800000 // q for q in range(1, bottom + 2 - horizon)]
    lists: list[tuple[int, ...]] = []
    identifiers: dict[tuple[int, ...], int] = {}
    phase_index: list[int] = []
    for phase in range(half_period):
        def painted(y: int) -> bool:
            return (depth[y - horizon] + phase) % 8000 < half_period

        assert painted(marked_top)  # other half-period exchanges both materials
        rows = (marked_top, *(y for y in range(marked_top + 1, bottom + 1)
                              if painted(y) != painted(y - 1)), bottom + 1)
        if rows not in identifiers:
            identifiers[rows] = len(lists)
            lists.append(rows)
        phase_index.append(identifiers[rows])
    assert len(lists) <= 256
    packed: list[int] = []
    offsets = []
    for rows in lists:
        offsets.append(len(packed))
        packed.extend(rows)
    q8_depth = [0] + [2048000 // q for q in range(1, bottom + 2 - horizon)]
    out = [
        "// Generated by docs/tasks/RALLY-15/generate_phase_table.py; do not edit.",
        "// Exact hundredth-unit phases. Half-period exchange flips the materials.",
        "#pragma once", "#include <stdint.h>", "namespace rally { namespace section_phase {",
        f"constexpr unsigned HalfPeriod={half_period}, MarkedTop={marked_top};",
        f"constexpr unsigned PatternCount={len(lists)};",
    ]

    def array(kind: str, name: str, values: list[int]) -> None:
        out.append(f"static const {kind} {name}[] = {{")
        for start in range(0, len(values), 24):
            out.append("    " + ",".join(map(str, values[start:start + 24])) + ",")
        out.append("};")

    array("uint8_t", "PhaseIndex", phase_index)
    array("uint16_t", "Offsets", offsets)
    array("uint8_t", "Rows", packed)
    array("int32_t", "DepthQ8", q8_depth)
    out.append("constexpr unsigned MaterialBytes=sizeof(PhaseIndex)+sizeof(Offsets)+sizeof(Rows);")
    out.append("constexpr unsigned TableBytes=MaterialBytes+sizeof(DepthQ8);")
    out.append("} }")
    return "\n".join(out) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="reject a stale generated header")
    args = parser.parse_args()
    path = Path(__file__).with_name("section_phase.hpp")
    content = generate()
    if args.check:
        if not path.exists() or path.read_text() != content:
            raise SystemExit(f"stale generated file: {path}")
        print("Phase header matches generator.")
    else:
        path.write_text(content)
        print(f"Generated {path.name}.")


if __name__ == "__main__":
    main()
