"""Generate the task-local stock-VDP road-section resident program.

Source-qualified protocol; native qualification/results are recorded separately.
Use the repository .venv/bin/python, with --check to check the generated header.
"""
import argparse
from pathlib import Path
import struct

ROOT = Path(__file__).resolve().parent
PARAM, VECTOR, COEFFICIENTS, PRODUCT, TRANSFORM, RED, WHITE, OUTPUT, DRAW_RED, DRAW_WHITE = range(30000, 30010)
BUFFER_IDS = tuple(range(PARAM, DRAW_WHITE + 1))

# P = [centreTop, centreBottom, yTop, yBottom, 1].  Product is the
# first two rows of the 4x4 transform, including its zero coefficients.
COEFFICIENT_VALUES = (
    0, 0, 1 / 50, 0, -96 / 50,
    -1, 1, 0, 0, 0,
    0, 0, -1 / 50, 1 / 50, 0,
    1, 0, 0, 0, 0,
    0, 0, 0, 0, 0,
    0, 0, -1, 1, 0,
    0, 0, 0, 0, 0,
    0, 0, 1, 0, 0,
)


def word(value):
    return struct.pack('<H', value & 0xffff)


def command(buffer, operation):
    return bytes((23, 0, 0xa0)) + word(buffer) + bytes((operation,))


def block(buffer, data):
    return command(buffer, 0) + word(len(data)) + data


def matrix(buffer, rows, columns, values):
    if len(values) != rows * columns:
        raise ValueError('matrix dimensions do not match supplied values')
    return command(buffer, 34) + bytes((0, rows, columns, 0)) + struct.pack('<' + 'f' * len(values), *values)


def strip(left, right, colour):
    data = bytes((18, 0, colour))
    for operation, u, v in ((4, left, 0), (4, right, 0), (0x55, left, 1), (0x55, right, 1)):
        # Three int16 coordinates become x,y,0: the last word is VDU 0 padding.
        data += bytes((25, operation)) + word(u) + word(v) + word(u * v)
    assert len(data) == 35
    return data


def strips(painted):
    result = [(-106, 106, 9 if painted else 15), (-90, 90, 8),
              (-86, -84, 11 if painted else 15), (84, 86, 11 if painted else 15)]
    if painted:
        result.append((-2, 2, 11))
    return result


def section_program(template):
    data = command(VECTOR, 34) + bytes((0x20, 5, 1, 0xc0)) + word(PARAM) + word(0)
    data += command(PRODUCT, 34) + bytes((6, 8, 1)) + word(COEFFICIENTS) + word(VECTOR)
    # Copy eight float32 coefficients into the first two rows.  The remaining
    # rows, matrix dimensions and the original templates remain unchanged.
    data += command(TRANSFORM, 5) + bytes((0xe2,)) + word(0) + word(32) + word(PRODUCT) + word(0)
    data += command(OUTPUT, 41) + bytes((0x4e, 0xc0)) + word(TRANSFORM) + word(template) + word(5) + word(8) + word(4)
    data += command(OUTPUT, 1)
    return data


def startup():
    data = bytes((23, 0, 0xf8)) + word(1) + word(1)
    for buffer in BUFFER_IDS:
        data += command(buffer, 2)
    data += block(PARAM, bytes(8) + word(1))
    data += matrix(COEFFICIENTS, 8, 5, COEFFICIENT_VALUES)
    data += matrix(TRANSFORM, 4, 4, [0] * 15 + [1])
    for template, painted in ((RED, True), (WHITE, False)):
        for left, right, colour in strips(painted):
            data += block(template, strip(left, right, colour))
    data += block(DRAW_RED, section_program(RED))
    data += block(DRAW_WHITE, section_program(WHITE))
    return data


def draw_section(centre_top, centre_bottom, y_top, y_bottom, painted):
    if not 104 <= y_top < y_bottom <= 224:
        raise ValueError('section must lie in the 120-row road viewport')
    values = (centre_top, centre_bottom, y_top, y_bottom)
    if not all(-32768 <= value <= 32767 for value in values):
        raise ValueError('section parameter outside signed-word range')
    # 8 payload bytes + 11 adjust-command bytes + 6 call-command bytes.
    return (command(PARAM, 5) + bytes((0xc2,)) + word(0) + word(8)
            + b''.join(word(value) for value in values)
            + command(DRAW_RED if painted else DRAW_WHITE, 1))


def cpp_header():
    data = startup()
    lines = [
        '// Generated by docs/tasks/RALLY-15/protocol.py. Do not edit.',
        '#pragma once', '#include "road.hpp"',
        'namespace rally { namespace section {',
        'static const uint8_t Startup[] = {',
    ]
    for offset in range(0, len(data), 16):
        lines.append('    ' + ','.join(str(value) for value in data[offset:offset + 16]) + ',')
    lines += [
        '};', 'constexpr unsigned StartupSize = sizeof(Startup);',
        'inline void buffered(Stream &out, unsigned id, unsigned operation) {',
        '    out.byte(23); out.byte(0); out.byte(160); out.word(id); out.byte(operation);',
        '}',
        '// Caller validates section bounds; appends exactly 25 UART bytes.',
        'inline void draw(Stream &out, int cxTop, int cxBottom, int yTop, int yBottom, bool painted) {',
        f'    buffered(out, {PARAM}, 5); out.byte(194); out.word(0); out.word(8);',
        '    out.word(cxTop); out.word(cxBottom); out.word(yTop); out.word(yBottom);',
        f'    buffered(out, painted ? {DRAW_RED} : {DRAW_WHITE}, 1);',
        '}', '}} // namespace rally::section', '',
    ]
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='reject a stale generated header')
    args = parser.parse_args()
    header = ROOT / 'section_protocol.hpp'
    expected = cpp_header()
    if args.check:
        if not header.exists() or header.read_text() != expected:
            raise SystemExit('section_protocol.hpp is missing or stale; run protocol.py')
    else:
        header.write_text(expected)
        output = ROOT / '.work'
        output.mkdir(exist_ok=True)
        (output / 'startup.vdu').write_bytes(startup())
        (output / 'sample-section.vdu').write_bytes(draw_section(140, 180, 116, 160, True))
    print(f'VDP section protocol: {len(startup())} startup bytes; 25 UART bytes/section; buffers 30000..30009.')


if __name__ == '__main__':
    main()
