"""Generate the isolated vehicle angle tables; no game files are changed."""
from pathlib import Path
import hashlib
import json
import math

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
TURN = 65536


def angle(radians):
    return int(math.floor(radians * TURN / math.tau + 0.5))


def generate():
    bearing = [angle(math.atan(x / 160)) for x in range(0, 513, 2)]
    cross_samples = list(range(0, 3585, 32)) + list(range(3592, 3969, 8)) + list(range(3969, 4097))
    heading = [angle(math.asin(x / 4096)) for x in cross_samples]
    assert len(bearing) == 257 and len(heading) == 289
    out = ["// Generated by generate_vehicle_tables.py; angle units are 1/65536 turn.",
           "#pragma once", "#include <stdint.h>", "namespace rally { namespace r18 {"]
    for name, values in (("BearingAngles", bearing), ("HeadingAngles", heading)):
        out.append(f"static const int16_t {name}[{len(values)}] = {{")
        for start in range(0, len(values), 12):
            out.append("    " + ",".join(map(str, values[start:start + 12])) + ",")
        out.append("};")
    out.append("} }")
    (HERE / "bearing_table.hpp").write_text("\n".join(out) + "\n")
    identities = {}
    for relative in ("rally/include/road.hpp", "rally/include/car.hpp", "rally/tools/build_car.py",
                     "rally/assets/car/sprites.json"):
        identities[relative] = hashlib.sha256((ROOT / relative).read_bytes()).hexdigest()
    (HERE / "vehicle-table-evidence.json").write_text(json.dumps({
        "generator": "generate_vehicle_tables.py", "angle_units_per_turn": TURN,
        "bearing": {"focal_pixels": 160, "max_abs_screen_offset": 512, "step_pixels": 2,
                    "entries": len(bearing), "bytes": len(bearing) * 2},
        "heading": {"input": "signed cross of Q12 tangents divided by4096",
                    "cross_samples": "0..3584 step32;3592..3968 step8;3969..4096 step1",
                    "entries": len(heading), "bytes": len(heading) * 2},
        "lookup_bytes": (len(bearing) + len(heading)) * 2,
        "source_sha256": identities,
    }, indent=2) + "\n")


if __name__ == "__main__":
    generate()
